### ISSUE TITLE
Where can I find the files T1w_restore_brain.nii and brainmask_fs.nii?

### ISSUE THREAD

**Issue by ronias** [MMTI/Toolkit_for_MIRA_LAB_Striatal_Segmentation#1]
I first want to run a test on your files, from where can I download them?

Thanks.

**Comment by jocwilliams** [comment]
Hello, T1w_restore_brain.nii is the T1w MR AC-PC aligned data you want to segment, and brainmask_fs.nii is the associated brain mask in that space.  Those are the file names for those in data preprocessed with the Human Connectome Project Minimal Preprocessing Pipelines (HCP MPP) - fMRIPrep or other preprocessing pipelines will have files that are potentially be named differently.

If you do not have any data of your own, you can try it with a subject from the Human Connectome Project - Young Adult.  
https://www.humanconnectome.org/study/hcp-young-adult
https://db.humanconnectome.org/
